### ISSUE TITLE
getting a login error. 

### ISSUE THREAD

**Issue by jeski** [sertalpbilal/FPL-Optimization-Tools#6]
script has been working fine until today.  I've created a team.json file and now getting the following error:

Login attempt failed, checking local file
Traceback (most recent call last):
  File "solve_regular.py", line 20, in <module>
    my_data = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sertalpbilal** [comment]
Hey @jeski, maybe there is an issue with the content of the `team.json` file? Does it look like a valid JSON to you?

**Comment by jeski** [comment]
thank you, that was it.
